-- 코드를 입력하세요
SELECT DISTINCT DATE_FORMAT(OS.SALES_DATE, '%Y') AS YEAR, 
       DATE_FORMAT(OS.SALES_DATE, '%m') AS MONTH,
       UI.GENDER,
       COUNT(DISTINCT OS.USER_ID) AS USERS
  FROM USER_INFO UI
  JOIN ONLINE_SALE OS ON (UI.USER_ID = OS.USER_ID)
 WHERE UI.GENDER IS NOT NULL
 GROUP BY YEAR, MONTH, UI.GENDER
 ORDER BY YEAR, MONTH, GENDER;