-- 코드를 입력하세요
SELECT CP3.CART_ID
  FROM (SELECT CP1.CART_ID, CP1.NAME
  FROM CART_PRODUCTS CP1
 WHERE CP1.NAME = "Milk"
UNION
SELECT CP2.CART_ID, CP2.NAME
  FROM CART_PRODUCTS CP2
 WHERE NAME = "Yogurt") AS CP3
 GROUP BY CP3.CART_ID
HAVING COUNT(CP3.CART_ID) = 2;