-- 코드를 입력하세요
SELECT MONTH(C1.START_DATE) AS MONTH,
       C1.CAR_ID, 
       COUNT(C1.CAR_ID) AS RECORDS
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C1
 WHERE MONTH(C1.START_DATE) IN (8, 9, 10)
 GROUP BY MONTH, C1.CAR_ID
HAVING CAR_ID IN (SELECT C2.CAR_ID
                    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C2
                   WHERE MONTH(C2.START_DATE) IN (8, 9, 10)
                   GROUP BY C2.CAR_ID
                  HAVING COUNT(C2.CAR_ID) >= 5)
 ORDER BY MONTH, C1.CAR_ID DESC;
