-- 코드를 입력하세요
SELECT 
  CASE 
       WHEN PRICE >= 0 AND PRICE < 10000
       THEN 0
       WHEN PRICE >= 10000
       THEN TRUNCATE(PRICE/10000, 0) * 10000
       END AS PRICE_GROUP, 
       COUNT(PRODUCT_ID) AS PRODUCTS
  FROM PRODUCT
 GROUP BY PRICE_GROUP
 ORDER BY PRICE_GROUP;
 