-- 코드를 입력하세요
SELECT CRH.HISTORY_ID,
  CASE WHEN (DATEDIFF(CRH.END_DATE, CRH.START_DATE) + 1 >= 7
        AND DATEDIFF(CRH.END_DATE, CRH.START_DATE) + 1 < 30)
       THEN TRUNCATE(RCC.DAILY_FEE * 
                     (DATEDIFF(CRH.END_DATE, CRH.START_DATE) + 1) * (100 - 
                     (SELECT CDP2.DISCOUNT_RATE
                        FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN CDP2
                       WHERE CDP2.DURATION_TYPE = '7일 이상'
                         AND CDP2.CAR_TYPE = '트럭')) / 100, 0)
       WHEN (DATEDIFF(CRH.END_DATE, CRH.START_DATE) + 1 >= 30
        AND DATEDIFF(CRH.END_DATE, CRH.START_DATE) + 1 < 90)
       THEN TRUNCATE(RCC.DAILY_FEE * 
                     (DATEDIFF(CRH.END_DATE, CRH.START_DATE) + 1) * (100 - 
                     (SELECT CDP2.DISCOUNT_RATE
                        FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN CDP2
                       WHERE CDP2.DURATION_TYPE = '30일 이상'
                         AND CDP2.CAR_TYPE = '트럭')) / 100, 0)
       WHEN DATEDIFF(CRH.END_DATE, CRH.START_DATE) + 1 >= 90
       THEN TRUNCATE(RCC.DAILY_FEE * 
                     (DATEDIFF(CRH.END_DATE, CRH.START_DATE) + 1) * (100 - 
                     (SELECT CDP2.DISCOUNT_RATE
                        FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN CDP2
                       WHERE CDP2.DURATION_TYPE = '90일 이상'
                         AND CDP2.CAR_TYPE = '트럭')) / 100, 0)
       ELSE RCC.DAILY_FEE * (DATEDIFF(CRH.END_DATE, CRH.START_DATE) + 1)
       END AS FEE
  FROM CAR_RENTAL_COMPANY_CAR RCC
  JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY CRH ON (RCC.CAR_ID = CRH.CAR_ID)
  JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN CDP ON (RCC.CAR_TYPE = CDP.CAR_TYPE)
 WHERE RCC.CAR_TYPE = '트럭'
 GROUP BY CRH.HISTORY_ID, RCC.CAR_TYPE
 ORDER BY FEE DESC, CRH.HISTORY_ID DESC;