-- 코드를 입력하세요
SELECT CRCC.CAR_ID
  FROM CAR_RENTAL_COMPANY_CAR CRCC
  JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY CRCRH ON (CRCC.CAR_ID = CRCRH.CAR_ID)
 WHERE CRCC.CAR_TYPE = '세단'
   AND CRCRH.START_DATE LIKE '2022-10%'
 GROUP BY CRCC.CAR_ID
 ORDER BY CRCC.CAR_ID DESC;